language:
  python

python:
  - 3.6

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - pip install --upgrade pytest

install:
  pip install -e .

script:
  py.test -vv --cov-report term-missing:skip-covered --cov=dilami_calendar

after_success:
  coveralls

deploy:
  provider: pypi
  user: "meyt"
  password:
    secure: "g7rybP6f8HU5cJfg7iOzXjanWardXEsjLS0r84Ed5dSV7Hw9N3gLdheDnXgxGfZPUofYE71qQSfGExjiDeQG6/mzwulaCWybODr2loWaquAvFH3tF6MgDhxBIC3iZ90ZHrpkHUE8oAh46dVcXIs5j7f40A/mzT0GJ18ymJEsFWzgSI22XjO9IkboT+5j8vN0wYSp1EHDbnDQsnVBAXraQMJYf0UWKmLhp9+S6Nv+8YqLSeok39A1YB3FEbaoGqk74LKZGRnkr8Js+3Jyc/lOI0AzS5XE8DQYEiuzAstLo4hDBPKxsF9tbn0eBI6mPwpwqVC8i8/SDhlFun0Sdicv4VBqtDWxZt1xkzHLNX0eEKrqXfU/YGifgjZI9S/fDLOork2IcJSVFzamrjWEWx+h+0tQmIC/AxL0O0BWBR3jArudqLD/9YFzQSuq6L65i9Ktx1evpNeBcOAUJOCripJJHZE9q2qINoiBahgNJp8soc3z8SgE8pv04YiTXfRkWfXO4BfX7tcPVXdxwbS4zBx85ZWcuUn/ggFzXAvkKW6Qw+yBZitKwZo/ZxrX82OQqRsmmAxNusADTT7B07GIZ6gBrHrJ6dQ5TIv1GQ0x9jA4CZs9qC/Ixi2S3v//BKx/wQYLeJtoapug5fm63LyujPJBuaXoDOo4/KA8jUkYMfs2CPY="
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip-cleanup: true
  skip_existing: true
